version: '3.8'
services:
  backend:
    image: zebangeth/campuscycle:backend-latest
    ports:
      - "3000:3000"
    # environment:
    #   - MONGODB_URI=mongodb://mongo:27017/CampusCycle # 示例 MongoDB URI, 根据需要进行调整
    depends_on:
      - mongo

  frontend:
    image: zebangeth/campuscycle:frontend-latest
    ports:
      - "3001:3001"

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

volumes:
  mongo-data:
