apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
      - name: backend
        image: zebangeth/campuscycle:backend-latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
        env:
        - name: MONGODB_URI
          value: mongodb://mongo-service:27017/CampusCycle